### ISSUE TITLE
Implement log fetching for Github Actions

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#124]
Fetching logs is not currently implemented.  This should be the relevant API:  https://docs.github.com/en/rest/reference/actions#download-workflow-run-logs

**Comment by ilveroluca** [comment]
It turns out that the Github API will return the logs only for authenticated requests, which means we need to implement authentication before this will work.

Also, the API returns a zip archive with one file per step in the run.  I tried a simple example and here are the contents of the zip that was returned:

```
$ find . | sort
.
./1_Generate OpenAPI docs (1).txt
./1_Generate OpenAPI docs.txt
./Generate OpenAPI docs
./Generate OpenAPI docs/10_Post Run actionscheckout@v2.txt
./Generate OpenAPI docs/11_Complete job.txt
./Generate OpenAPI docs/1_Set up job.txt
./Generate OpenAPI docs/2_Run actionscheckout@v2.txt
./Generate OpenAPI docs/3_Generate docs.txt
./Generate OpenAPI docs/4_Setup assets.txt
./Generate OpenAPI docs/5_Publish docs.txt
```

**Comment by simleo** [comment]
I tried downloading the logs zip for [this workflow](https://github.com/detekt/detekt/blob/5048b8bf0bb6a64de80f3d0b5aa25f694d71167d/.github/workflows/pre-merge.yaml). For every job there's a global `.txt` log file and a directory containing a separate log file for each step in that job. The job log is essentially a concatenation of the step logs (except that the leading timestamps don't match exactly), plus a two-line preamble that looks like:

```
2021-07-04T11:05:27.6372473Z Found online and idle hosted runner(s) in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-07-04T11:05:27.6372611Z Waiting for a hosted runner in 'organization' to pick this job...
```

The "gradle" job has a 3 x 3 matrix, which leads to 9 jobs being run, one for each parameter combination. Together with the non-parametric jobs, this leads to 11 subfolders:

```
compile-test-snippets
'gradle (macos-latest, 11)'
'gradle (macos-latest, 16)'
'gradle (macos-latest, 8)'
'gradle (ubuntu-latest, 11)'
'gradle (ubuntu-latest, 16)'
'gradle (ubuntu-latest, 8)'
'gradle (windows-latest, 11)'
'gradle (windows-latest, 16)'
'gradle (windows-latest, 8)'
verify-generated-config-file
```

**Comment by kikkomep** [comment]
obsoleted by #167
