### ISSUE TITLE
Feature: import workflow from a GitHub repository

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#149]
The API already supports the submission of a workflow from an arbitrary link to an RO-Crate. It would be nice to also be able to point to a GitHub repository whose layout conforms to that of a Workflow (Testing) RO-Crate (basically, it needs to have an `ro-crate-metadata.json` file at the top level). A good example is any of the [IWC workflows](https://github.com/iwc-workflows/).

**Comment by ilveroluca** [comment]
This feature has been implemented through the GitHub app.  The feature is also available directly through the API, but it's not documented.  The caller can specify the link to a Git repository for the `roc_link` property given to the [POST /users/current/workflows](https://api.lifemonitor.eu/static/apidocs.html#post-/users/current/workflows) API call.

This feature should be documented, but that's for another issue.
