### ISSUE TITLE
Link to API docs in API web app

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#163]
It would be nice to have a link to the API docs somewhere in the API web app. The link should take you to the live API docs for that specific LM instance, e.g., a link to https://api.lifemonitor.eu/static/apidocs.html from https://api.lifemonitor.eu/profile.

Not sure where to put the link though. Maybe in the "API Keys" tab?

**Comment by ilveroluca** [comment]
This has been fixed.  There's now a link in the API Keys tab.
