### ISSUE TITLE
Improve handling of nonexistent workflow version submission

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#171]
If someone tries to submit a nonexistent workflow version from WorkflowHub, e.g.:

```javascript
{'identifier': '138',
 'name': 'sars-cov-2-consensus-from-variation/COVID-19-CONSENSUS-CONSTRUCTION',
 'version': '999'}
```

We currently reply with a misleading error message:

```javascript
{'detail': 'RO Crate processing exception',
 'type': 'about:blank',
 'extra_info': {'exception': '[400] Bad request: Downloaded RO-crate has bad zip format'},
 'title': 'Bad Request',
 'status': 400,
 'instance': 'https://api.lifemonitor.eu/registries/b556d831-a393-43bd-8047-98505b7fc20c/workflows'}
```

The problem is that [WorkflowHub does not reply to such requests with an error](https://github.com/seek4science/seek/issues/778), so we end up trying to unzip an HTML page.

**Comment by simleo** [comment]
Finn says:

> There is a workaround, where you can pass the HTTP header: `Accept: application/json` and you will get a 400 error with a JSON response in case of error, but still get the binary zip file if it is valid.

**Comment by kikkomep** [comment]
fixed in https://github.com/crs4/life_monitor/pull/377
