### ISSUE TITLE
Fix `roc_link` returned for workflow

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#18]
At the moment, LM is returning an RO-crate link that is computes based on the WorkflowHub address that it has been provided through the settings, rather than returning the original ROC link that was used to import the workflow.  This should be changed:  if the RO-crate link is stored, it must be the original (correct) one.

**Comment by kikkomep** [comment]
The original RO-crate link is now stored as property of the Workflow model (see https://github.com/crs4/life_monitor/commit/bf057021ffbece592be45754883b0c265c293352)
