### ISSUE TITLE
Future import pins min Python version to 3.7

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#25]
In our code we have:

```python
from __future__ import annotations
```

In several places. Apparently this is [available only since Python 3.7](https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7). If we want to support earlier versions of Python we should consider whether we really need the feature enabled by this import (or annotations at all).

**Comment by ilveroluca** [comment]
Good question.  Given that the goal of the project is to build a service, not a library to be integrated in other software, I think supporting the development process is a much higher priority than avoiding "special" requirements.  Considering that LM runs as a containerized service it would be relatively simple to satisfy even stricter version requirements.

Also, Python 3.7 has already been out for two years, so it isn't that new. Moreover:
* 3.6 will only be supported for less than 2 more years;
* 3.5 will get its final release this week;
* previous releases no longer receive security updates.

Thus, IMHO it's ok to pin the minimum Python version to 3.7.
