### ISSUE TITLE
Missing config file check does not create PR when `main` branch becomes available

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#255]
I installed the LM app on a completely empty repository.  The first check that runs is the "Missing config file" check.  It noticed that the LM configuration file was missing.  I suppose because there was no branch onto which to open a PR, it opened an issue with the text:

```
No lifemonitor.yaml configuration file found on this repository.
The lifemonitor.yaml should be placed on the root of this repository.
```

I later created a `main` branch, but the check did not open a PR with a configuration template.

Suggested fix.
* If reasonably feasible, the check should notice that the branch has been created after its first run and create a PR with the configuration template.  It would also be nice if the check could add a comment to the original issue referencing the new PR, or alternatively if it could close the issue.
* If this is too hard, we should at least extend the text of the issue to provide a link to a template file for the configuration and maybe even to the documentation on how to complete it.

**Comment by kikkomep** [comment]
fixed in https://github.com/crs4/life_monitor/pull/378
