### ISSUE TITLE
Make the lifemonitor.yaml configuration file hidden

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#259]
Perhaps we should rename the LM configuration file from `lifemonitor.yaml` to `.lifemonitor.yaml`.  This would make the file hidden during the users' day-to-day operations.  After all, the file is not part of the application code.

@simleo, @kikkomep: what do you think?

**Comment by simleo** [comment]
Yes. The Dockstore configuration file also starts with a dot (`.dockstore.yml`). By the way, I think LM should accept both `.lifemonitor.yaml` and `.lifemonitor.yml`, since both extensions are frequently used, so it's easy to get it wrong.

**Comment by ilveroluca** [comment]
Resolved by PR #276
