### ISSUE TITLE
branch/tag switches on GH integration configuration form are not clear

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#261]
The meaning of the switch controls on [the GH integration configuration](https://api.dev.lifemonitor.eu/profile?currentView=githubSettingsTab) is not clear when the switch is off.  If the switches are all off it's not obvious that one can turn them on to enable the setting for "all" branches or tags.

We should at least have a tooltip.

![lm_gh_integration_settings](https://user-images.githubusercontent.com/1502936/200624134-e6e5bec9-3e83-4d0f-851f-0d1f8b99451f.png)

**Comment by kikkomep** [comment]
fixed in #277
