### ISSUE TITLE
Add text label to search boxes on dashboard

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#263]
At the moment we have two search boxes on the dashboard.  Actually, one (the top) is a real search box, while the other is a "filter" to be applied to the dashboard.

There needs to be labels better explaining what these are.  It's not obvious.

Proposed label for the top:  "Search LifeMonitor for workflows"
Proposed label for filter: "Filter you dashboard"

**Comment by kikkomep** [comment]
fixed by https://github.com/crs4/lifemonitor-web/pull/41
