### ISSUE TITLE
Dashboard title "My workflows" is misleading

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#264]
The LM dashboard is titled "My Workflows".  But, it actually shows my workflows, plus any workflows to which I'm subscribed, plus any search results.  Overall the title "My Workflows" is quite misleading.

Perhaps simply "Dashboard" would be a better title, to avoid creating confusion.

**Comment by kikkomep** [comment]
fixed by https://github.com/crs4/lifemonitor-web/pull/42
