### ISSUE TITLE
Some workflows marked as private are visible to the public

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#268]
Some workflows marked as private are visible to the public.  Here is an example:
<https://app.lifemonitor.eu/workflow;uuid=3e4b4b1c-1074-4453-9cc8-68634c80ea5a>

Although it's not mine, I can find this workflow through the dashboard if I search for the word "Cheminformatics". I can see some of its metadata.  I can't see its test results.  I can subscribe to receive notifications about it, although I don't know what information the notifications would contain (I haven't received any).

**Comment by kikkomep** [comment]
Yes, we can.
