### ISSUE TITLE
Remove "Suites" column from Dashboard

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#282]
It looks like pretty much all workflows have a single test suite.  I propose we remove the "Suites" column from the dashboard since it doesn't seem very useful for most (all?) cases.

What do you think @kikkomep @simleo

**Comment by ilveroluca** [comment]
I'm not suggesting to remove suites as a concept, but just removing the
column from the table.

Il lun 21 nov 2022, 17:40 Simone Leo ***@***.***> ha scritto:

**Comment by simleo** [comment]
The main advantage would be helping visualization in small screens. Otherwise, I don't think it hurts that much.
