### ISSUE TITLE
Cache content in RepositoryFile.get_content?

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#298]
Should `RepositoryFile.get_content` cache content to `self._content` after reading on [line 87](https://github.com/crs4/life_monitor/blob/211edd0d1418fdfa440c67d6433d9e99eff61b3d/lifemonitor/api/models/repositories/files/base.py#L87)?

https://github.com/crs4/life_monitor/blob/211edd0d1418fdfa440c67d6433d9e99eff61b3d/lifemonitor/api/models/repositories/files/base.py#L87

**Comment by kikkomep** [comment]
fixed in https://github.com/crs4/life_monitor/pull/347
