### ISSUE TITLE
Error displayed when authorizing LM as an OAuth client application

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#30]
The following error is displayed when authorizing LM as an OAuth client application (e.g., when you click on "Authorize" on the WFHub page for the LM application and `https://lm.org:8443/oauth2/auth/seek?code=...` is called):

```
authlib.integrations.base_client.errors.OAuthError: invalid_request: Missing required parameter: redirect_uri
```

However, a subsequent login as Seek on LM works.

**Comment by kikkomep** [comment]
Fixed in release [v0.1.0](https://github.com/crs4/life_monitor/releases/tag/0.1.1)
