### ISSUE TITLE
Link connected account IDs to profile page on IdP service

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#313]
On the LifeMonitor user profile page we have an "Account" tab with a section "Connected Accounts".  The connected accounts table shows the IDs of the external accounts.  It would be useful to have the IDs link to the relevant page in the connected service.

* WorkflowHub: https://workflowhub.eu/people/<user id>
* dev.WorkflowHub: https://dev.workflowhub.eu/people/<user id>
* GitHub: https://github.com/<username>
* LS Login: https://profile.aai.lifescience-ri.eu/profile

**Comment by kikkomep** [comment]
fixed in #371
