### ISSUE TITLE
Cannot register new account via github

### ISSUE THREAD

**Issue by hexylena** [crs4/life_monitor#321]
![Screenshot 2023-05-23 at 17-12-59 Life Monitor](https://github.com/crs4/life_monitor/assets/458683/3f4d3820-a8be-4d43-bb4f-617cb8bcd6de)

![Screenshot 2023-05-23 at 17-13-05 https __app lifemonitor eu](https://github.com/crs4/life_monitor/assets/458683/0ee6590b-1cde-4739-ae3a-a924970a9786)

**Comment by kikkomep** [comment]
The issue has already been fixed. The update will deployed as soon as possible

**Comment by hexylena** [comment]
Thanks @kikkomep !

**Comment by hexylena** [comment]
Ahh LS Login is also not working, after joining the test VO I get a 502 bad gateway, the generated URL looks like:

https://app.lifemonitor.eu/oauth2/authorized/lsaai?state=...&scope=openid+email+orcid+profile+eduperson_principal_name&code=...%3D%3D&iss=https%3A%2F%2Fproxy.aai.lifescience-ri.eu&client_id=APP-5696071B-AAC7-4ABE-A477-DFD9BCF91DE3

**Comment by hexylena** [comment]
And same response for WorkflowHub as for Github, I guess I need to be more patient for the redeployment :)

**Comment by kikkomep** [comment]
Hi @hexylena ! The deployment of the updated version is now online. 
There might still be issues with "LS Login" as we are migrating its support to production. 
Let us know if it works as expected, and thanks for reporting this issue.

**Comment by hexylena** [comment]
This works as expected! LS login connected as well :)
