### ISSUE TITLE
Link to rocrate download actually points to the home

### ISSUE THREAD

**Issue by hexylena** [crs4/life_monitor#322]
e.g. https://app.lifemonitor.eu/workflow;uuid=deae0ae0-7b65-013b-cdda-005056ab5db4;version=1

workflow ROCrate: [https://api.lifemonitor.eu/workflows/deae0ae0-7b65-013b-cdda-005056ab5db4/rocrate/1/download](https://app.lifemonitor.eu/)

the link there is to a strange place, rather than the api download route. (I ctrl-clicked it at first.)

**Comment by kikkomep** [comment]
The link was not set up correctly. With the latest version of the web app (0.5.2), it should be fine.
