### ISSUE TITLE
GH app errors starting from "empty" repo

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#331]
I started https://github.com/simleo/test_lm_gh_app with only `LICENSE` and `README.md`, then installed the GitHub app on the repo. This resulted in https://github.com/simleo/test_lm_gh_app/pull/1, which once merged created:
 * a `.lifemonitor.yaml`
 * a sample workflow and associated Planemo test files
 * a GitHub workflow to run the above tests
 * an RO-Crate metadata file

I've found two problems:
 * The RO-Crate metadata file does not have a test suite / test instance
 * After the merge, LM created https://github.com/simleo/test_lm_gh_app/issues/2 saying that the LifeMonitor configuration file is not valid

**Comment by ilveroluca** [comment]
The full PR #338, with contributions from both @kikkomep and @ilveroluca, addresses this issue.  You won't be able to see the fix in effect in the GitHub app until the changes are deployed to production (though they should be visible if you run the checks locally).
