### ISSUE TITLE
Review handling of invalid service URLs

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#54]
As mentioned in #53, the `http://invalidurl:8080` (added in b6b480c38a20caf8118c09a6d4f9937b8b8a3369) was generating an error condition not expected by the [current test case](https://github.com/crs4/life_monitor/blob/df9f8f3c764ba9a9997bff42ceab6f4926d1ffae/tests/integration/api/services/test_services.py#L48), causing a [test failure](https://github.com/crs4/life_monitor/runs/1681741203?check_suite_focus=true#step:6:1277) that was fixed by reverting the URL to the previous `http://127.0.0.1:67890` value. Since `http://invalidurl:8080` is, of course, an address that could be encountered in the metadata, the current code should be investigated to find out why the two different types of invalid url generate a different behavior and the test coverage expanded to handle currently unhandled cases.

Note: on my laptop the test failed with an `[Errno 111] Connection refused` rather than `[Errno -2] Name or service not known` as on the GitHub build. I think this might have something to do with a weird behavior by my provider's DNS that seems to map unknown addresses to localhost, but the thing is that the code should take into account the fact that "Name or service not known" is not the only possible error.

**Comment by ilveroluca** [comment]
The code that should be responsible for this problem has been revised since the bug was opened.  It's *probably* been fixed...
