### ISSUE TITLE
Broken code in check_health

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#81]
The `check_health` methods in `api/models/workflows.py` [refer to a nonexistent `last_test_build` attribute of testing service objects](https://github.com/crs4/life_monitor/blob/de866e5716ba4b0ebc41f1ebabb5edb79bf239a6/lifemonitor/api/models/workflows.py#L177).

The problem can be triggered by changing `test_services.py` as follows:

```diff
--- a/tests/integration/api/services/test_services.py
+++ b/tests/integration/api/services/test_services.py
@@ -229,7 +229,7 @@ def test_workflow_registration_not_allowed_user(app_client, user1, user2):
 
 
 def test_workflow_serialization(app_client, user1):
-    _, workflow = utils.pick_and_register_workflow(user1)
+    _, workflow = utils.pick_and_register_workflow(user1, "sort-and-change-case-invalid-service-url")
     assert isinstance(workflow, models.WorkflowVersion), "Workflow not properly initialized"
     data = workflow.to_dict(test_suite=True, test_build=True, test_output=True)
     assert isinstance(data, dict), "Invalid serialization output type"
```

Without the above change, the test picks a workflow without test instances (actually depending on the order in which workflows were uploaded to the test wfhub service -- this is what happens with the current Seek data tarball), so the broken code is not run.

Discussed today with @kikkomep: apparently the whole set of `to_dict` methods (and their dependencies, such as `check_health`) in the various classes is not actively used/tested anymore and thus is likely outdated.

**Comment by ilveroluca** [comment]
This has been solved.
