### ISSUE TITLE
Centralize entry point for documentation

### ISSUE THREAD

**Issue by ilveroluca** [crs4/life_monitor#84]
We have decided to have as a central entry point for documentation [this repository's github page](https://crs4.github.io/life_monitor/).

* Move all but basic content from the README to the documentation on github pages
    * keep a basic description, the makefile commands, and a pionter to the docs on github pages
* Same thing for the [root of the wiki](https://github.com/crs4/life_monitor/wiki)

**Comment by simleo** [comment]
- [x] wiki root
- [ ] update gh pages
- [ ] update readme
