### ISSUE TITLE
Allow to get full log for a test job

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#97]
Current calls for getting test logs have a hardcoded 131072 (128K) bytes limit for the log size, which is too large for "summary calls" (see #94) while not allowing to get the full log in the specific call. The options I see are:

* Allow a zero or negative `limit_bytes` to specify that the full content is desired (negative values could even work as in Python indexing)
* **AFTER ADDRESSING #94**, change the default to return the full log

We could do both, actually.

**Comment by simleo** [comment]
Discussed at the 2021-05-20 meeting. Allowing to get an arbitrary amount of bytes could overload the service, so we decided that the way to get the full log should be through repeated calls with different offsets. To avoid the need for too many calls, OTOH, we also agreed to **change the default bytes limit to something close to the typical maximum allowed log size in CIs**. I think it's around 4MB for Travis.

**Comment by kikkomep** [comment]
obsoleted by #167
