### ISSUE TITLE
Travis job logs are stitched together

### ISSUE THREAD

**Issue by simleo** [crs4/life_monitor#98]
When a Travis build maps to multiple jobs, we are currently stitching all job logs together to form a single "build log" (see [get_test_build_output](https://github.com/crs4/life_monitor/blob/ea91f384a0b9475c682e84a1458842ae86835832/lifemonitor/api/models/services/travis.py#L158)). I don't think this is very useful to the caller: where does each log end? Additionally, due to #97, the caller is likely to get only part of the first log.

A quick fix could be to return a list of strings (which would contain a single element in the Jenkins case).

A more long-term solution could be to increase our model's granularity so that it can map to different levels of CI runs.

**Comment by simleo** [comment]
Created a [card](https://github.com/crs4/life_monitor/projects/1#card-60499512) for the "more long term solution" thing.

**Comment by kikkomep** [comment]
obsoleted by #167
